# Generated by Django 3.1.7 on 2021-08-06 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('dtp_times', models.IntegerField(default=0, verbose_name='dtp_times')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
