version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  main:
    build: .
    command: bash -c "
      sleep 5 &&
      python cars/manage.py migrate &&
      cd cars &&
      gunicorn cars.wsgi:application --bind 0.0.0.0:8000 --reload"
      # python cars/manage.py runserver 0.0.0.0:8000
    #command: bash -c make
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
  nginx:
    image: nginx:alpine
    restart: on-failure
    depends_on:
      - main
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

